//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace cfg.cfg
{ 
    public enum EActorType
    {
        /// <summary>
        /// 战士
        /// </summary>
        Warriod = 1,
        /// <summary>
        /// 法师
        /// </summary>
        Master = 2,
        /// <summary>
        /// 盗贼
        /// </summary>
        Thieves = 3,
        /// <summary>
        /// 牧师
        /// </summary>
        Minister = 4,
    }

} 
