//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.cfg
{
   
public partial class TbActor
{
    private readonly Dictionary<int, cfg.actor> _dataMap;
    private readonly List<cfg.actor> _dataList;
    
    public TbActor(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, cfg.actor>();
        _dataList = new List<cfg.actor>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            // cfg.actor _v;
            // _v = cfg.actor.Deserializeactor(_buf);
            // _dataList.Add(_v);
            // _dataMap.Add(_v.ID, _v);
        }
        PostInit();
    }

    public Dictionary<int, cfg.actor> DataMap => _dataMap;
    public List<cfg.actor> DataList => _dataList;

    public cfg.actor GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public cfg.actor Get(int key) => _dataMap[key];
    public cfg.actor this[int key] => _dataMap[key];

    public void Resolve(Dictionary<string, object> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}