//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;



namespace cfg
{ 
public partial class Tables
{
    public cfg.TbActor TbActor {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        var tables = new System.Collections.Generic.Dictionary<string, object>();
        TbActor = new cfg.TbActor(loader("cfg_tbactor")); 
        tables.Add("cfg.TbActor", TbActor);

        PostInit();
        TbActor.Resolve(tables); 
        PostResolve();
    }

    public void TranslateText(System.Func<string, string, string> translator)
    {
        TbActor.TranslateText(translator); 
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}