//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace cfg.cfg
{
public sealed partial class actor :  Bright.Config.BeanBase 
{
    public actor(ByteBuf _buf) 
    {
        ID = _buf.ReadInt();
        Name = _buf.ReadString();
        Dec = _buf.ReadString();
        HP = _buf.ReadInt();
        MP = _buf.ReadInt();
        Attack = _buf.ReadInt();
        Defensive = _buf.ReadInt();
        ActorType = (cfg.EActorType)_buf.ReadInt();
        PostInit();
    }

    public static actor Deserializeactor(ByteBuf _buf)
    {
        return new cfg.actor(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public int ID { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 背景
    /// </summary>
    public string Dec { get; private set; }
    /// <summary>
    /// 血量
    /// </summary>
    public int HP { get; private set; }
    /// <summary>
    /// 蓝量
    /// </summary>
    public int MP { get; private set; }
    /// <summary>
    /// 攻击力
    /// </summary>
    public int Attack { get; private set; }
    /// <summary>
    /// 防御力
    /// </summary>
    public int Defensive { get; private set; }
    /// <summary>
    /// 角色类型
    /// </summary>
    public cfg.EActorType ActorType { get; private set; }

    public const int __ID__ = 1456815083;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, object> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "Dec:" + Dec + ","
        + "HP:" + HP + ","
        + "MP:" + MP + ","
        + "Attack:" + Attack + ","
        + "Defensive:" + Defensive + ","
        + "ActorType:" + ActorType + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}

}